### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by ignatov** [iantmoore/substeps-intellij-plugin#14]
com/intellij/execution/JavaRunConfigurationExtensionManager

java.lang.NoClassDefFoundError: com/intellij/execution/JavaRunConfigurationExtensionManager
	at uk.co.itmoore.intellisubsteps.execution.SubstepsRunConfiguration.writeExternal(SubstepsRunConfiguration.java:148)
	at com.intellij.execution.configurations.ModuleBasedConfiguration.clone(ModuleBasedConfiguration.java:104)
	at com.intellij.execution.configurations.ModuleBasedConfiguration.clone(ModuleBasedConfiguration.java:41)
	at com.intellij.execution.configurations.ConfigurationFactory.createConfiguration(ConfigurationFactory.java:50)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:170)
	at com.intellij.execution.RunManager.createRunConfiguration(RunManager.kt:142)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfigurationStatic(RunConfigurationProducer.java:236)
	at com.intellij.execution.actions.RunConfigurationProducer.cloneTemplateConfiguration(RunConfigurationProducer.java:226)
	at com.intellij.execution.actions.RunConfigurationProducer.createConfigurationFromContext(RunConfigurationProducer.java:87)
	at com.intellij.execution.actions.RunConfigurationProducer.findOrCreateConfigurationFromContext(RunConfigurationProducer.java:178)
	at com.intellij.execution.actions.PreferredProducerFind.getConfigurationsFromContext(PreferredProducerFind.java:116)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup.populateWithDynamicRunners(ChooseRunConfigurationPopup.java:1039)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup.createSettingsList(ChooseRunConfigurationPopup.java:1019)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup$ConfigurationListPopupStep.<init>(ChooseRunConfigurationPopup.java:391)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup$ConfigurationListPopupStep.<init>(ChooseRunConfigurationPopup.java:382)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup.<init>(ChooseRunConfigurationPopup.java:77)
	at com.intellij.execution.actions.ChooseRunConfigurationPopupAction.actionPerformed(ChooseRunConfigurationPopupAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:355)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:343)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:767)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.intellij.execution.JavaRunConfigurationExtensionManager PluginClassLoader[uk.co.itmoore.intellisubsteps, 1.0.7] com.intellij.ide.plugins.cl.PluginClassLoader@2ca405c9
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 60 more

**Comment by iantmoore** [comment]
thanks for raising - I guess this is from an anonymous crash report from a user ?  can you tell the version of the plugin or IntelliJ that has generated the error ?  

In the last version of the plugin I restricted the install to Java only projects, I think it's possible to get this error in versions prior to v1.0.8 by installing the plugin in non Java based projects... ?

**Comment by ignatov** [comment]
Yes, it's an anonymous report.
Gogland 172.3757, plugin version 1.0.7.

**Comment by iantmoore** [comment]
Hmm, tricky one... Because I hadn't limited the products in which the plugin should operate, it's now found it's way into some products it shouldn't have.  the 1.0.8 version with the product limitation in there won't have rolled out to Gogland users and the 1.0.7 version, they're stuck on that version.

Unless I can think of another approach, I think I need to create a 1.0.9 that is available across products, check the product (ApplicationInfo, I think ?) on start up (?) or wherever substeps code is invoked and if not a Java product, pop a notification or dialog suggesting the user should uninstall / deactivate the plugin for that product...  

Then create a 1.0.10 that is restricted..
